### ISSUE TITLE
Not able to deploy Kitura app to Bluemix.

### ISSUE THREAD

**Issue by nightshiftdev** [IBM-Bluemix/Kitura-Starter#52]
Steps to reproduce:

1. Follow all steps at: http://www.kitura.io/en/starter/gettingstarted.html

2. Deploy using Kitura-Starter: http://www.kitura.io/en/starter/deploying.html
bx app push APP_NAME_HERE

Expected:

```
Uploading kijowski-swift-test...
Uploading app files from: /Users/pkijowski/projects/server/kijowski-swift-test
Uploading 14.5M, 1350 files
Done uploading               
OK
```

Actual:
```
FAILED
Error uploading application.
The resource file mode is invalid: File mode '0444' is invalid.
MacBook-Pro-16:kijowski-swift-test pkijowski$ bx app push kijowski-swift-test -v
Incorrect Usage.
```

--------
Files with incorrect permissions:
find . -type f -perm 0444
./.build/repositories/BlueSocket.git-3162807777605905816/objects/pack/pack-dfcf8de75c9f422107fc6e774846308f2568da60.idx
./.build/repositories/BlueSocket.git-3162807777605905816/objects/pack/pack-dfcf8de75c9f422107fc6e774846308f2568da60.pack
./.build/repositories/BlueSSLService.git--6577639804771281610/objects/pack/pack-f8ff754837b52e2a7c1b382a9bc6d27a07f19cc7.idx
./.build/repositories/BlueSSLService.git--6577639804771281610/objects/pack/pack-f8ff754837b52e2a7c1b382a9bc6d27a07f19cc7.pack
./.build/repositories/CCurl.git-8026296523752779197/objects/pack/pack-0cb6a4836483f9d5b1defc93155140bf1eec1336.idx
./.build/repositories/CCurl.git-8026296523752779197/objects/pack/pack-0cb6a4836483f9d5b1defc93155140bf1eec1336.pack
./.build/repositories/Kitura-net.git--7410958935072501107/objects/pack/pack-0f98324702568fe8129507b4644a256d5f991091.idx
./.build/repositories/Kitura-net.git--7410958935072501107/objects/pack/pack-0f98324702568fe8129507b4644a256d5f991091.pack
./.build/repositories/Kitura-TemplateEngine.git--5059963620657797085/objects/pack/pack-da6c888b229a1afff830ba7b87c3096f6c402fc7.idx
./.build/repositories/Kitura-TemplateEngine.git--5059963620657797085/objects/pack/pack-da6c888b229a1afff830ba7b87c3096f6c402fc7.pack
./.build/repositories/Kitura.git-6522211175291160341/objects/pack/pack-a97626e5e37b0122ff9dae47b2dd07ea05f7c9e9.idx
./.build/repositories/Kitura.git-6522211175291160341/objects/pack/pack-a97626e5e37b0122ff9dae47b2dd07ea05f7c9e9.pack
./.build/repositories/LoggerAPI.git--6449715459278086880/objects/pack/pack-0fc0b4ba84e394bf85d7a05eeb363c58aa219b68.idx
./.build/repositories/LoggerAPI.git--6449715459278086880/objects/pack/pack-0fc0b4ba84e394bf85d7a05eeb363c58aa219b68.pack
./.build/repositories/SwiftyJSON.git--6955445084174387031/objects/pack/pack-80997e32d3bd5ec7f813544cc14c877ca2ecadc4.idx
./.build/repositories/SwiftyJSON.git--6955445084174387031/objects/pack/pack-80997e32d3bd5ec7f813544cc14c877ca2ecadc4.pack

---------
Workaround: 
```
find . -type f -perm 0444 -exec chmod a+rwx {} \;
```

**Comment by rolivieri** [comment]
@nightshiftdev Just catching up with these issues. Glad you were able to figure out what was wrong in #53. 

Regarding this issue that is still open, are you still having problems deploying to Bluemix? Also, are you having problems deploying Kitura-Starter AS-IS or are you trying to deploy another Kitura-based application to Bluemix? Just asking because I could not reproduce the problems you described above when I pushed (`bx app push`) Kitura-Starter AS-IS.

**Comment by nightshiftdev** [comment]
Hi @rolivieri, thanks for your prompt response.

You are correct, I am able to deploy Kitura-Starter As-Is (with minor name changes in Package.swift and manifest.yml). However, I have a barebone project https://github.com/nightshiftdev/kijowski-swift-test that I created following the instructions from http://www.kitura.io/en/starter/gettingstarted.html and http://www.kitura.io/en/starter/deploying.html; that project gives me the following error when uploading the project to Bluemix:

```
The resource file mode is invalid: File mode '0444' is invalid.
```

What is the difference between my "Hello World" project and Kitura-Starter?

I realize this might not be the correct repo for this defect, but  I am not sure where else to get help with this issue.

Thanks!

**Comment by rolivieri** [comment]
@nightshiftdev No worries, for future reference, feel free to ask question in our slack org: swift-at-ibm.slack.com. We have several channels (e.g. bluemix, kitura, etc.) there that you can use for support. 

Going over your issue above, can you try adding the following file to your project (adjust its contents as needed) and then push your app again: https://github.com/IBM-Bluemix/Kitura-Starter/blob/master/.cfignore. This file should reside in the root folder of your project.

**Comment by nightshiftdev** [comment]
@rolivieri adding cfignore file did the trick. Thank you for your help.
