### ISSUE TITLE
Not currently deployable via the "Deploy to Bluemix" button

### ISSUE THREAD

**Issue by NocturnalSolutions** [IBM-Bluemix/Kitura-Starter#55]
I'm following along with the [Bluemix course](https://developer.ibm.com/courses/all/bluemix-essentials/?course=begin#5237) and currently on a page which teaches us to deploy an application using the "Deploy to Bluemix" button on a GitHub repo's main page; however, since I'm a Swift developer, I'm trying to do so with this repo instead of the Node one in the example. However, upon clicking the button, deployment is failing. After going into the logs, I'm seeing: 

```
FAILED
Server error, status code: 400, error code: 100001, message: The app is invalid: health_check_http_endpoint HTTP health check endpoint is not a valid URI path: 

Finished: FAILED
```

I tried cloning the repo and fiddling with the `health-check-http-endpoint` value in manifest.yml, but couldn't coax things into deploying successfully.

I got to the point where I was looking through the CloudFoundry code to try to figure out what it was expecting, and I found [where things seem to be going wrong](https://github.com/cloudfoundry/cloud_controller_ng/blob/4799c76cb6532dbf39ff72446928ddb80c7d0f32/spec/unit/lib/cloud_controller/diego/protocol_spec.rb#L249-L257), but… how is that even code? Ruby is weird.

Can anyone else replicate the failure at least?

**Comment by rolivieri** [comment]
@NocturnalSolutions Thanks for letting us know about this issue. We just made a few minor changes to the `manifest.yml` file. Can you try deploying one more time?

**Comment by NocturnalSolutions** [comment]
@rolivieri [Success!](http://kitura-starter-20170715034729114-heartbreaking-kicksorter.mybluemix.net) Thanks for that. I'll continue working through the Bluemix tutorial tomorrow.
